
package mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-21T17:59:14.270-05:00
 * Generated source version: 2.4.1
 * 
 */
public final class RegistrarSolicitudTransferenciaImputadoSSPExporter_RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudTransferenciaImputadoSSPExporterImplService");

    private RegistrarSolicitudTransferenciaImputadoSSPExporter_RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistrarSolicitudTransferenciaImputadoSSPExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistrarSolicitudTransferenciaImputadoSSPExporterImplService ss = new RegistrarSolicitudTransferenciaImputadoSSPExporterImplService(wsdlURL, SERVICE_NAME);
        RegistrarSolicitudTransferenciaImputadoSSPExporter port = ss.getRegistrarSolicitudTransferenciaImputadoSSPExporterImplPort();  
        
        {
        System.out.println("Invoking registrarSolicitudTransferenciaImputadoSSP...");
        mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado.SolicitudTrasladoImputadoWSDTO _registrarSolicitudTransferenciaImputadoSSP_arg0 = null;
        try {
            port.registrarSolicitudTransferenciaImputadoSSP(_registrarSolicitudTransferenciaImputadoSSP_arg0);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
