
package mx.gob.segob.nsjp.ws.cliente.solicituddefensor;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-09T12:54:43.890-05:00
 * Generated source version: 2.4.1
 * 
 */
public final class RegistrarSolicitudDefensorAreaExternaExporter_RegistrarSolicitudDefensorAreaExternaExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudDefensorAreaExternaExporterImplService");

    private RegistrarSolicitudDefensorAreaExternaExporter_RegistrarSolicitudDefensorAreaExternaExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RegistrarSolicitudDefensorAreaExternaExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RegistrarSolicitudDefensorAreaExternaExporterImplService ss = new RegistrarSolicitudDefensorAreaExternaExporterImplService(wsdlURL, SERVICE_NAME);
        RegistrarSolicitudDefensorAreaExternaExporter port = ss.getRegistrarSolicitudDefensorAreaExternaExporterImplPort();  
        
        {
        System.out.println("Invoking registrarSolicitudDefensor...");
        mx.gob.segob.nsjp.ws.cliente.solicituddefensor.SolicitudDefensorWSDTO _registrarSolicitudDefensor_arg0 = null;
        try {
            mx.gob.segob.nsjp.ws.cliente.solicituddefensor.SolicitudDefensorWSDTO _registrarSolicitudDefensor__return = port.registrarSolicitudDefensor(_registrarSolicitudDefensor_arg0);
            System.out.println("registrarSolicitudDefensor.result=" + _registrarSolicitudDefensor__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
