
package mx.gob.segob.nsjp.ws.cliente.enviardocumentoincumplimientomedida;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-11-03T20:06:01.884-06:00
 * Generated source version: 2.4.1
 * 
 */
public final class EnviarDocumentoIncumplimientoMedidaExporter_EnviarDocumentoIncumplimientoMedidaExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarDocumentoIncumplimientoMedidaExporterImplService");

    private EnviarDocumentoIncumplimientoMedidaExporter_EnviarDocumentoIncumplimientoMedidaExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EnviarDocumentoIncumplimientoMedidaExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EnviarDocumentoIncumplimientoMedidaExporterImplService ss = new EnviarDocumentoIncumplimientoMedidaExporterImplService(wsdlURL, SERVICE_NAME);
        EnviarDocumentoIncumplimientoMedidaExporter port = ss.getEnviarDocumentoIncumplimientoMedidaExporterImplPort();  
        
        {
        System.out.println("Invoking enviarDocumentoDeIncumplimientoDeMedida...");
        mx.gob.segob.nsjp.ws.cliente.enviardocumentoincumplimientomedida.DocumentoWSDTO _enviarDocumentoDeIncumplimientoDeMedida_arg0 = null;
        java.lang.String _enviarDocumentoDeIncumplimientoDeMedida_arg1 = "";
        java.lang.String _enviarDocumentoDeIncumplimientoDeMedida_arg2 = "";
        try {
            java.lang.Long _enviarDocumentoDeIncumplimientoDeMedida__return = port.enviarDocumentoDeIncumplimientoDeMedida(_enviarDocumentoDeIncumplimientoDeMedida_arg0, _enviarDocumentoDeIncumplimientoDeMedida_arg1, _enviarDocumentoDeIncumplimientoDeMedida_arg2);
            System.out.println("enviarDocumentoDeIncumplimientoDeMedida.result=" + _enviarDocumentoDeIncumplimientoDeMedida__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
