
package mx.gob.segob.nsjp.ws.cliente.seguimiento;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-01T14:08:14.265-05:00
 * Generated source version: 2.4.1
 * 
 */
public final class ActualizarSeguimientoMandamientoMedidaExporter_ActualizarSeguimientoMandamientoMedidaExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ActualizarSeguimientoMandamientoMedidaExporterImplService");

    private ActualizarSeguimientoMandamientoMedidaExporter_ActualizarSeguimientoMandamientoMedidaExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ActualizarSeguimientoMandamientoMedidaExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ActualizarSeguimientoMandamientoMedidaExporterImplService ss = new ActualizarSeguimientoMandamientoMedidaExporterImplService(wsdlURL, SERVICE_NAME);
        ActualizarSeguimientoMandamientoMedidaExporter port = ss.getActualizarSeguimientoMandamientoMedidaExporterImplPort();  
        
        {
        System.out.println("Invoking actualizarSeguimiento...");
        mx.gob.segob.nsjp.ws.cliente.seguimiento.SeguimientoMandamientoMedidaWSDTO _actualizarSeguimiento_arg0 = new SeguimientoMandamientoMedidaWSDTO();
        try {
            _actualizarSeguimiento_arg0.setFolioDocumento("vlad pax");
            port.actualizarSeguimiento(_actualizarSeguimiento_arg0);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
