
package mx.gob.segob.nsjp.ws.cliente.consultaraudiencia;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-06-05T19:35:39.916-05:00
 * Generated source version: 2.4.1
 * 
 */
public final class ConsultarAudienciasByFechasYEstatusExporter_ConsultarAudienciasByFechasYEstatusExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarAudienciasByFechasYEstatusExporterImplService");

    private ConsultarAudienciasByFechasYEstatusExporter_ConsultarAudienciasByFechasYEstatusExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultarAudienciasByFechasYEstatusExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConsultarAudienciasByFechasYEstatusExporterImplService ss = new ConsultarAudienciasByFechasYEstatusExporterImplService(wsdlURL, SERVICE_NAME);
        ConsultarAudienciasByFechasYEstatusExporter port = ss.getConsultarAudienciasByFechasYEstatusExporterImplPort();  
        
        {
        System.out.println("Invoking consultarAudienciasByFechasYEstatus...");
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciasByFechasYEstatus_arg0 = null;
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO> _consultarAudienciasByFechasYEstatus__return = port.consultarAudienciasByFechasYEstatus(_consultarAudienciasByFechasYEstatus_arg0);
            System.out.println("consultarAudienciasByFechasYEstatus.result=" + _consultarAudienciasByFechasYEstatus__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarAudienciaById...");
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciaById_arg0 = null;
        try {
            mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciaById__return = port.consultarAudienciaById(_consultarAudienciaById_arg0);
            System.out.println("consultarAudienciaById.result=" + _consultarAudienciaById__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking consultarAudienciasPorFechasYSolicitudTranscripcion...");
        mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO _consultarAudienciasPorFechasYSolicitudTranscripcion_arg0 = null;
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultaraudiencia.AudienciaDefensoriaWSDTO> _consultarAudienciasPorFechasYSolicitudTranscripcion__return = port.consultarAudienciasPorFechasYSolicitudTranscripcion(_consultarAudienciasPorFechasYSolicitudTranscripcion_arg0);
            System.out.println("consultarAudienciasPorFechasYSolicitudTranscripcion.result=" + _consultarAudienciasPorFechasYSolicitudTranscripcion__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
