package mx.gob.segob.nsjp.ws.cliente.solicitud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2012-09-03T17:47:32.421-05:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/", name = "EnviarSolicitudServiceExporterImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface EnviarSolicitudServiceExporterImpl {

    @WebResult(name = "return", targetNamespace = "")
    @Action(input = "http://impl.ws.service.nsjp.segob.gob.mx/EnviarSolicitudServiceExporterImpl/recibirSolicitudRequest", output = "http://impl.ws.service.nsjp.segob.gob.mx/EnviarSolicitudServiceExporterImpl/recibirSolicitudResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://impl.ws.service.nsjp.segob.gob.mx/EnviarSolicitudServiceExporterImpl/recibirSolicitud/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "recibirSolicitud", targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitud.RecibirSolicitud")
    @WebMethod
    @ResponseWrapper(localName = "recibirSolicitudResponse", targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitud.RecibirSolicitudResponse")
    public mx.gob.segob.nsjp.ws.cliente.solicitud.SolicitudWSDTO recibirSolicitud(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.solicitud.SolicitudWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
