
package mx.gob.segob.nsjp.ws.cliente.consultardistritos;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-06-08T18:31:26.175-05:00
 * Generated source version: 2.4.2
 * 
 */
public final class ConsultarDistritosServiceWSExporter_ConsultarDistritosServiceWSExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "ConsultarDistritosServiceWSExporterImplService");

    private ConsultarDistritosServiceWSExporter_ConsultarDistritosServiceWSExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ConsultarDistritosServiceWSExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ConsultarDistritosServiceWSExporterImplService ss = new ConsultarDistritosServiceWSExporterImplService(wsdlURL, SERVICE_NAME);
        ConsultarDistritosServiceWSExporter port = ss.getConsultarDistritosServiceWSExporterImplPort();  
        
        {
        System.out.println("Invoking consultarDistritos...");
        try {
            java.util.List<mx.gob.segob.nsjp.ws.cliente.consultardistritos.CatDistritoWSDTO> _consultarDistritos__return = port.consultarDistritos();
            System.out.println("consultarDistritos.result=" + _consultarDistritos__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
