package mx.gob.segob.nsjp.ws.enable.moreliapj;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-11-19T11:56:32.692-06:00
 * Generated source version: 2.7.0
 * 
 */
@WebServiceClient(name = "MoreliaBridgePJ", 
                  wsdlLocation = "http://localhost:49663/MoreliaBridgePJ.asmx?wsdl",
                  targetNamespace = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/") 
public class MoreliaBridgePJ extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://moreliapj.enable.ws.nsjp.segob.gob.mx/", "MoreliaBridgePJ");
    public final static QName MoreliaBridgePJSoap12 = new QName("http://moreliapj.enable.ws.nsjp.segob.gob.mx/", "MoreliaBridgePJSoap12");
    public final static QName MoreliaBridgePJSoap = new QName("http://moreliapj.enable.ws.nsjp.segob.gob.mx/", "MoreliaBridgePJSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:49663/MoreliaBridgePJ.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MoreliaBridgePJ.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:49663/MoreliaBridgePJ.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MoreliaBridgePJ(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MoreliaBridgePJ(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MoreliaBridgePJ() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MoreliaBridgePJ(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MoreliaBridgePJ(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MoreliaBridgePJ(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns MoreliaBridgePJSoap
     */
    @WebEndpoint(name = "MoreliaBridgePJSoap12")
    public MoreliaBridgePJSoap getMoreliaBridgePJSoap12() {
        return super.getPort(MoreliaBridgePJSoap12, MoreliaBridgePJSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoreliaBridgePJSoap
     */
    @WebEndpoint(name = "MoreliaBridgePJSoap12")
    public MoreliaBridgePJSoap getMoreliaBridgePJSoap12(WebServiceFeature... features) {
        return super.getPort(MoreliaBridgePJSoap12, MoreliaBridgePJSoap.class, features);
    }
    /**
     *
     * @return
     *     returns MoreliaBridgePJSoap
     */
    @WebEndpoint(name = "MoreliaBridgePJSoap")
    public MoreliaBridgePJSoap getMoreliaBridgePJSoap() {
        return super.getPort(MoreliaBridgePJSoap, MoreliaBridgePJSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoreliaBridgePJSoap
     */
    @WebEndpoint(name = "MoreliaBridgePJSoap")
    public MoreliaBridgePJSoap getMoreliaBridgePJSoap(WebServiceFeature... features) {
        return super.getPort(MoreliaBridgePJSoap, MoreliaBridgePJSoap.class, features);
    }

}
