package mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-21T17:59:14.395-05:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "RegistrarSolicitudTransferenciaImputadoSSPExporterImplService", 
                  wsdlLocation = "http://localhost:8080/nsjp-web/RegistrarSolicitudTransferenciaImputadoSSPExporterImplService?wsdl",
                  targetNamespace = "http://impl.ws.service.nsjp.segob.gob.mx/") 
public class RegistrarSolicitudTransferenciaImputadoSSPExporterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudTransferenciaImputadoSSPExporterImplService");
    public final static QName RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/nsjp-web/RegistrarSolicitudTransferenciaImputadoSSPExporterImplService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RegistrarSolicitudTransferenciaImputadoSSPExporterImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/nsjp-web/RegistrarSolicitudTransferenciaImputadoSSPExporterImplService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RegistrarSolicitudTransferenciaImputadoSSPExporterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RegistrarSolicitudTransferenciaImputadoSSPExporterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RegistrarSolicitudTransferenciaImputadoSSPExporterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }    

    /**
     *
     * @return
     *     returns RegistrarSolicitudTransferenciaImputadoSSPExporter
     */
    @WebEndpoint(name = "RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort")
    public RegistrarSolicitudTransferenciaImputadoSSPExporter getRegistrarSolicitudTransferenciaImputadoSSPExporterImplPort() {
        return super.getPort(RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort, RegistrarSolicitudTransferenciaImputadoSSPExporter.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegistrarSolicitudTransferenciaImputadoSSPExporter
     */
    @WebEndpoint(name = "RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort")
    public RegistrarSolicitudTransferenciaImputadoSSPExporter getRegistrarSolicitudTransferenciaImputadoSSPExporterImplPort(WebServiceFeature... features) {
        return super.getPort(RegistrarSolicitudTransferenciaImputadoSSPExporterImplPort, RegistrarSolicitudTransferenciaImputadoSSPExporter.class, features);
    }

}
