package mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-09-21T17:59:14.379-05:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", name = "RegistrarSolicitudTransferenciaImputadoSSPExporter")
@XmlSeeAlso({ObjectFactory.class})
public interface RegistrarSolicitudTransferenciaImputadoSSPExporter {

    @Action(input = "http://ws.service.nsjp.segob.gob.mx/RegistrarSolicitudTransferenciaImputadoSSPExporter/registrarSolicitudTransferenciaImputadoSSPRequest", output = "http://ws.service.nsjp.segob.gob.mx/RegistrarSolicitudTransferenciaImputadoSSPExporter/registrarSolicitudTransferenciaImputadoSSPResponse", fault = {@FaultAction(className = NSJPNegocioException_Exception.class, value = "http://ws.service.nsjp.segob.gob.mx/RegistrarSolicitudTransferenciaImputadoSSPExporter/registrarSolicitudTransferenciaImputadoSSP/Fault/NSJPNegocioException")})
    @RequestWrapper(localName = "registrarSolicitudTransferenciaImputadoSSP", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado.RegistrarSolicitudTransferenciaImputadoSSP")
    @WebMethod
    @ResponseWrapper(localName = "registrarSolicitudTransferenciaImputadoSSPResponse", targetNamespace = "http://ws.service.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado.RegistrarSolicitudTransferenciaImputadoSSPResponse")
    public void registrarSolicitudTransferenciaImputadoSSP(
        @WebParam(name = "arg0", targetNamespace = "")
        mx.gob.segob.nsjp.ws.cliente.solicitudtransferenciaimputado.SolicitudTrasladoImputadoWSDTO arg0
    ) throws NSJPNegocioException_Exception;
}
