
package mx.gob.segob.nsjp.ws.cliente.enviarcarpetainvestigacion;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2011-11-15T18:21:16.125-06:00
 * Generated source version: 2.4.1
 * 
 */
public final class EnviarCarpetaDeInvestigacionExporter_EnviarCarpetaDeInvestigacionExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarCarpetaDeInvestigacionExporterImplService");

    private EnviarCarpetaDeInvestigacionExporter_EnviarCarpetaDeInvestigacionExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EnviarCarpetaDeInvestigacionExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EnviarCarpetaDeInvestigacionExporterImplService ss = new EnviarCarpetaDeInvestigacionExporterImplService(wsdlURL, SERVICE_NAME);
        EnviarCarpetaDeInvestigacionExporter port = ss.getEnviarCarpetaDeInvestigacionExporterImplPort();  
        
        {
        System.out.println("Invoking enviarCarpetaDeInvestigacion...");
        mx.gob.segob.nsjp.ws.cliente.enviarcarpetainvestigacion.ExpedienteWSDTO _enviarCarpetaDeInvestigacion_arg0 = null;
        java.lang.String _enviarCarpetaDeInvestigacion_arg1 = "";
        java.lang.String _enviarCarpetaDeInvestigacion_arg2 = "";
        try {
            java.lang.Long _enviarCarpetaDeInvestigacion__return = port.enviarCarpetaDeInvestigacion(_enviarCarpetaDeInvestigacion_arg0, _enviarCarpetaDeInvestigacion_arg1, _enviarCarpetaDeInvestigacion_arg2);
            System.out.println("enviarCarpetaDeInvestigacion.result=" + _enviarCarpetaDeInvestigacion__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
