
package mx.gob.segob.nsjp.ws.cliente.enviarinformepolicialhomologado;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.4.2
 * 2012-02-22T11:08:35.948-06:00
 * Generated source version: 2.4.2
 * 
 */
public final class EnviarInformePolicialHomologadoExporter_EnviarInformePolicialHomologadoExporterImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.ws.service.nsjp.segob.gob.mx/", "EnviarInformePolicialHomologadoExporterImplService");

    private EnviarInformePolicialHomologadoExporter_EnviarInformePolicialHomologadoExporterImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = EnviarInformePolicialHomologadoExporterImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EnviarInformePolicialHomologadoExporterImplService ss = new EnviarInformePolicialHomologadoExporterImplService(wsdlURL, SERVICE_NAME);
        EnviarInformePolicialHomologadoExporter port = ss.getEnviarInformePolicialHomologadoExporterImplPort();  
        
        {
        System.out.println("Invoking enviarInformePolicialHomologado...");
        mx.gob.segob.nsjp.ws.cliente.enviarinformepolicialhomologado.InformePolicialHomologadoWSDTO _enviarInformePolicialHomologado_arg0 = null;
        java.lang.Long _enviarInformePolicialHomologado_arg1 = null;
        try {
            java.lang.Long _enviarInformePolicialHomologado__return = port.enviarInformePolicialHomologado(_enviarInformePolicialHomologado_arg0, _enviarInformePolicialHomologado_arg1);
            System.out.println("enviarInformePolicialHomologado.result=" + _enviarInformePolicialHomologado__return);

        } catch (NSJPNegocioException_Exception e) { 
            System.out.println("Expected exception: NSJPNegocioException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
