package mx.gob.segob.nsjp.ws.enable.moreliapj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2013-11-19T11:56:32.684-06:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/", name = "MoreliaBridgePJSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface MoreliaBridgePJSoap {

    @WebResult(name = "SolicitarAudienciaResult", targetNamespace = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/")
    @RequestWrapper(localName = "SolicitarAudiencia", targetNamespace = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.enable.moreliapj.SolicitarAudiencia")
    @WebMethod(operationName = "SolicitarAudiencia", action = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/SolicitarAudiencia")
    @ResponseWrapper(localName = "SolicitarAudienciaResponse", targetNamespace = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/", className = "mx.gob.segob.nsjp.ws.enable.moreliapj.SolicitarAudienciaResponse")
    public java.lang.String solicitarAudiencia(
        @WebParam(name = "xmlSolicitud", targetNamespace = "http://moreliapj.enable.ws.nsjp.segob.gob.mx/")
        java.lang.String xmlSolicitud
    );
}
